require ("prototypes.mapGenGastronomia")

require ("prototypes.item")
require ("prototypes.recipe")
require ("prototypes.recipe-category")
require ("prototypes.technology")
require ("prototypes.planet")
require ("prototypes.gastronomia")
require ("prototypes.gastronomiaConnection")
require ("prototypes.wine")
require ("prototypes.grapeTree")
require ("prototypes.assembling-machine")